name: Update shadPS4QtLauncher AUR Package

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update-aur:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get latest shadPS4QtLauncher release data
        id: get_release
        run: |
          sudo apt-get update && sudo apt-get install -y jq

          RELEASE_DATA=$(curl -s https://api.github.com/repos/shadps4-emu/shadps4-qtlauncher/releases | jq '.[0]')

          TAG_NAME=$(echo "$RELEASE_DATA" | jq -r '.tag_name')
          # TAG_NAME format: shadPS4QtLauncher-2025-10-18-4c9efe028e673fbfdb507b9a627fa5bd94bdcd6d
          # Extract parts: shadPS4QtLauncher-YYYY-MM-DD-FULLCOMMIT
          FULL_COMMIT=$(echo "$TAG_NAME" | awk -F'-' '{print $NF}')
          SHORT_COMMIT=$(echo "$FULL_COMMIT" | cut -c1-7)
          DATE_PART=$(echo "$TAG_NAME" | awk -F'-' '{print $2"-"$3"-"$4}')
          PKGVER_DATE_PART=$(echo "$DATE_PART" | sed 's/-/./g')
          PKGVER="${PKGVER_DATE_PART}.${SHORT_COMMIT}"

          LINUX_QT_URL=$(echo "$RELEASE_DATA" | jq -r '.assets[] | select(.name | contains("shadps4-qtlauncher") and endswith(".zip")) | .browser_download_url' | head -n1)

          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "pkgver=$PKGVER" >> $GITHUB_OUTPUT
          echo "date_part=$DATE_PART" >> $GITHUB_OUTPUT
          echo "short_commit=$SHORT_COMMIT" >> $GITHUB_OUTPUT
          echo "full_commit=$FULL_COMMIT" >> $GITHUB_OUTPUT
          echo "linux_qt_url=$LINUX_QT_URL" >> $GITHUB_OUTPUT

          echo "Latest release tag: $TAG_NAME"
          echo "Package version: $PKGVER"
          echo "Linux Qt URL: $LINUX_QT_URL"

      - name: Setup SSH for AUR
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/aur
          chmod 600 ~/.ssh/aur
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 aur.archlinux.org >> ~/.ssh/known_hosts
          cat > ~/.ssh/config << EOF
          Host aur.archlinux.org
            IdentityFile ~/.ssh/aur
            User aur
          EOF
          chmod 600 ~/.ssh/config

      - name: Clone AUR repository
        run: |
          git clone ssh://aur@aur.archlinux.org/shadps4-qtlauncher-bin.git aur-repo

      - name: Check if update needed
        id: check_update
        run: |
          CURRENT_VER=$(grep '^pkgver=' aur-repo/PKGBUILD | cut -d'=' -f2)
          NEW_VER="${{ steps.get_release.outputs.pkgver }}"

          echo "Current AUR version: $CURRENT_VER"
          echo "New version: $NEW_VER"

          if [ "$CURRENT_VER" = "$NEW_VER" ]; then
            echo "needs_update=false" >> $GITHUB_OUTPUT
            echo "No update needed"
          else
            echo "needs_update=true" >> $GITHUB_OUTPUT
            echo "Update needed!"
          fi

      - name: Download shadPS4QtLauncher artifacts
        if: steps.check_update.outputs.needs_update == 'true'
        run: |
          mkdir -p artifacts
          DATE_PART="${{ steps.get_release.outputs.date_part }}"
          SHORT_COMMIT="${{ steps.get_release.outputs.short_commit }}"

          if [ -n "${{ steps.get_release.outputs.linux_qt_url }}" ]; then
            echo "Downloading Qt zip..."
            curl -L "${{ steps.get_release.outputs.linux_qt_url }}" -o "artifacts/shadps4-qtlauncher-${DATE_PART}-${SHORT_COMMIT}.zip"
          fi

          ls -lh artifacts/

      - name: Create or update release with artifacts
        if: steps.check_update.outputs.needs_update == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_release.outputs.tag_name }}
          name: shadPS4QtLauncher ${{ steps.get_release.outputs.pkgver }}
          body: |
            Mirror of shadPS4QtLauncher build for AUR package.

            **Original Release:** ${{ steps.get_release.outputs.tag_name }}
            **Commit:** ${{ steps.get_release.outputs.full_commit }}
            **Date:** ${{ steps.get_release.outputs.date_part }}
          artifacts: "artifacts/*"
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          makeLatest: true
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PKGBUILD with mirror URLs
        if: steps.check_update.outputs.needs_update == 'true'
        run: |
          PKGVER="${{ steps.get_release.outputs.pkgver }}"
          DATE_PART="${{ steps.get_release.outputs.date_part }}"
          SHORT_COMMIT="${{ steps.get_release.outputs.short_commit }}"
          FULL_COMMIT="${{ steps.get_release.outputs.full_commit }}"
          TAG_NAME="${{ steps.get_release.outputs.tag_name }}"

          REPO_URL="https://github.com/${{ github.repository }}"
          SOURCE_URL="${REPO_URL}/releases/download/${TAG_NAME}/shadps4-qtlauncher-${DATE_PART}-${SHORT_COMMIT}.zip"

          cd aur-repo

          sed -i "s/^pkgver=.*/pkgver=${PKGVER}/" PKGBUILD
          sed -i "s/^_date=.*/_date=${DATE_PART}/" PKGBUILD
          sed -i "s/^_commit=.*/_commit=${FULL_COMMIT}/" PKGBUILD
          sed -i "s/^_shortcommit=.*/_shortcommit=${SHORT_COMMIT}/" PKGBUILD
          sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD

          sed -i "s|source=(\"shadps4-qtlauncher-.*|source=(\"shadps4-qtlauncher-\${_date}-\${_shortcommit}.zip::${SOURCE_URL}\")|" PKGBUILD

      - name: Generate .SRCINFO
        if: steps.check_update.outputs.needs_update == 'true'
        run: |
          docker run --rm -v "$(pwd)/aur-repo:/pkg" -w /pkg archlinux:latest bash -c "
            pacman -Sy --noconfirm base-devel &&
            useradd -m builder &&
            cp PKGBUILD /tmp/ &&
            chown builder:builder /tmp/PKGBUILD &&
            cd /tmp &&
            su builder -c 'makepkg --printsrcinfo' > /pkg/.SRCINFO
          "

          sudo chown -R $USER:$USER aur-repo

      - name: Update AUR repository
        if: steps.check_update.outputs.needs_update == 'true'
        run: |
          cd aur-repo

          git config user.name "mdmrk"
          git config user.email "mariodavo.20@gmail.com"

          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes detected in AUR repository"
            exit 0
          fi

          git add PKGBUILD .SRCINFO
          git commit -m "Update shadps4-qtlauncher-bin to version ${{ steps.get_release.outputs.pkgver }}"
          git push origin master

      - name: Update local repository
        if: steps.check_update.outputs.needs_update == 'true'
        run: |
          cp aur-repo/PKGBUILD .
          cp aur-repo/.SRCINFO .

          git config user.name "mdmrk"
          git config user.email "mariodavo.20@gmail.com"

          git add PKGBUILD .SRCINFO
          git commit -m "Update to version ${{ steps.get_release.outputs.pkgver }}"
          git push

      - name: Create summary
        if: steps.check_update.outputs.needs_update == 'true'
        run: |
          echo "## shadPS4QtLauncher AUR Package Updated! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **New Version:** ${{ steps.get_release.outputs.pkgver }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit SHA:** ${{ steps.get_release.outputs.short_commit }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Mirror Release:** https://github.com/${{ github.repository }}/releases/tag/${{ steps.get_release.outputs.tag_name }}" >> $GITHUB_STEP_SUMMARY

      - name: No update needed
        if: steps.check_update.outputs.needs_update == 'false'
        run: |
          echo "## No Update Needed ✓" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "shadps4-qtlauncher-bin package is already up to date." >> $GITHUB_STEP_SUMMARY
